ARG GO_VERSION=1.15.2

FROM golang:${GO_VERSION}-alpine AS builder

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /api
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN cd src && go build -a -installsuffix cgo -o /go/bin/hello

FROM alpine:latest

WORKDIR /api
COPY --from=builder /go/bin/hello /api/bin/hello


EXPOSE 8080
ENTRYPOINT ["/api/bin/hello"]