image: golang

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - go mod download

stages:
  - pre
  - test
  - build
  - publish
  - post

.mongo:
  services:
    - mongo:latest
  variables:
    MONGO_INITDB_ROOT_USERNAME: banterbus
    MONGO_INITDB_ROOT_PASSWORD: banterbus
    MONGO_INITDB_DATABASE: banterbus
  before_script:
    - go mod download
    - export BANTER_BUS_DB_HOST="mongo"

.private-key:
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - git config --global user.email "bot@haseebmajid.dev"
    - git config --global user.name "Banter Bus Bot"
    - mkdir -p ~/.ssh
    - touch ~/.ssh/known_host


create:merge-request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: pre
  before_script: []
  except:
    - master
    - tags
  script:
    - gitlab_auto_mr -t master -c WIP -d .gitlab/merge_request_templates/merge_request.md -r -s --use-issue-name

publish-docker:test:
  stage: pre
  only:
    - master
  image: docker
  services:
    - docker:dind
  before_script: []
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/api/Dockerfile -t ${CI_REGISTRY_IMAGE}:test .
    - docker push ${CI_REGISTRY_IMAGE}:test

include:
  - project: "tymonx/gitlab-ci"
    ref: v0.69.0
    file: "/templates/generic/go.yml"

lint:
  stage: test
  extends: .go-lint
  only:
    - merge_request

format:check:
  stage: test
  extends: .go-format
  only:
    - merge_request

lint:commits:
  image: node
  stage: test
  only:
    - merge_request
  before_script: []
  script:
    - npm install -g @commitlint/cli @commitlint/config-conventional
    - git fetch origin ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - commitlint --from=origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} --to=origin/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}

coverage:
  stage: test
  image: golang
  only:
    - merge_request
    - master
  services:
    - mongo
  variables:
    MONGO_INITDB_ROOT_USERNAME: banterbus
    MONGO_INITDB_ROOT_PASSWORD: banterbus
    MONGO_INITDB_DATABASE: banterbus
  script:
    - export BANTER_BUS_DB_HOST="mongo"
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/t-yuki/gocover-cobertura
    - go get -u github.com/jstemmer/go-junit-report
    - make coverage 2>&1 | go-junit-report > junit.xml
    - gocover-cobertura < coverage.out > cobertura.xml
  coverage: '/coverage: \d+.\d+% of statements/'
  artifacts:
      when: always
      reports:
          junit: junit.xml
          cobertura: cobertura.xml

publish:openapi:
  image: golang:latest
  stage: publish
  only:
    - master
  extends:
    - .private-key
  allow_failure: true
  script:
    - go mod download
    - make update-openapi
    - git status
    - git add specs/openapi.json
    - 'git commit -m "docs: Update Openapi" -m "Commit by Banter Bus Bot. Update openapi.json."'
    - git push


trigger:swagger-ui:build:
  image: curlimages/curl
  stage: publish
  only:
    - master
  script:
    -  "curl -X POST -F token=${BANTER_BUS_DOCS_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/22432967/trigger/pipeline"

create:gitlab:release:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  stage: post
  only:
    - /^release/.*$/
  before_script: []
  script:
    - gitlab_auto_release -c CHANGELOG.md -d "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/gitlab-automation-toolkit/gitlab-auto-release."
