app:
  logLevel: DEBUG
  environment: development
database:
  host: banter-bus-database
  port: 27017
  user: banterbus
  password: banterbus
  name: banterbus
webserver:
  host: 0.0.0.0
  port: 8080
