app:
  logLevel: DEBUG
  environment: development
database:
  host: banter-bus-database
  port: 27017
  user: banterbus
  password: banterbus
  name: banterbus
  authDB: admin
webserver:
  cors: ["http://localhost:3000", "http://localhost:8080"]
  host: 0.0.0.0
  port: 8080
