version: "3"

services:
  api:
    container_name: banter-bus-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ${PWD}/internal/:/api/internal/
      - ${PWD}/cmd/:/api/cmd/
    depends_on:
      - database

  database:
    container_name: banter-bus-database
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=banterbus
      - MONGO_INITDB_ROOT_PASSWORD=banterbus
      - MONGO_INITDB_DATABASE=banterbus
    volumes:
      - /data/db
    ports:
      - 27017:27017

  database-gui:
    container_name: banter-bus-database-gui
    image: mongoclient/mongoclient:4.0.1
    depends_on:
      - database
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://banterbus:banterbus@banter-bus-database:27017
    volumes:
      - /data/db mongoclient/mongoclient
    ports:
      - 3000:3000

  database-seed:
    container_name: banter-bus-database-seed
    image: registry.gitlab.com/banter-bus/banter-bus-tests/database-seed:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=banterbus
      - MONGO_INITDB_ROOT_PASSWORD=banterbus
      - MONGO_INITDB_DATABASE=banterbus
      - MONGO_HOSTNAME=banter-bus-database:27017
    depends_on:
      - database
