version: "3"

services:
  # server:
  #   container_name: banter-bus-nginx
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   ports:
  #     - 443:443
  #   depends_on:
  #     - api

  api:
    container_name: banter-bus-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src/:/api/src/
    depends_on:
      - mongodb

  mongodb:
    container_name: banter-bus-database
    image: mongo:latest
    env_file: docker/database/.env
    volumes:
      - /data/db
    ports:
      - 27017:27017

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    depends_on:
      - mongodb
    volumes:
      - /data/db mongoclient/mongoclient
    ports:
      - 3000:3000

  redis:
    container_name: message_broker
    image: redis:latest
    volumes:
      - /var/lib/redis
    ports:
      - 6379:6379
