version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: 1.16
    volumes:
      - ..:/workspace:cached
      - banterbus-shell-history:{{ .HistoryPath }}
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:database
    user: vscode
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  banterbus-shell-history:
